# pihole-dns - an Ansible playbook to configure a recursive PiHole DNS server
# Copyright (C) 2024  Charles German <5donuts@pm.me>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
- name: Enable UFW logging
  community.general.ufw:
    logging: "on"

- name: Deny all traffic by default
  community.general.ufw:
    policy: deny

- name: Allow TCP traffic from trusted networks
  community.general.ufw:
    rule: allow
    proto: tcp
    src: "{{ item }}"
  loop: "{{ firewall_allowed_cidrs }}"

- name: Allow UDP traffic from trusted networks
  community.general.ufw:
    rule: allow
    proto: udp
    src: "{{ item }}"
  loop: "{{ firewall_allowed_cidrs }}"

- name: Enable UFW
  community.general.firewall:
    state: enabled
